spring.application.name=patitas-urbanas-api
server.port=3000

spring.datasource.url=jdbc:postgresql://localhost:5433/patitas_urbanas
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.show-sql=false

logging.level.org.hibernate.stat=DEBUG
logging.level.org.hibernate.SQL=DEBUG

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
