spring.application.name=patitas-urbanas-api
server.port=3000

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB:patitas_urbanas}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:adminpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
